// <auto-generated>
// 此文件由 EquipmentRegistryPlugin 自动生成，请勿手动修改
// </auto-generated>
using System;
using System.Collections.Generic;

public static class EquipmentRegistry
{
    public static readonly Dictionary<string, Type> Map = new Dictionary<string, Type>()
    {
        { "sword_001", typeof(SunnyFarm.code.Equipments.Sword.Sword001) },
    };
}
